# Generated by Django 4.1.2 on 2022-10-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notes_delete_react'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
